---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_h: 128
          hue_l: 0
          lightness_h: 255
          lightness_l: 109 # 140
          saturation_h: 95
          saturation_l: 0
        yellow:
          hue_h: 50
          hue_l: 10
          lightness_h: 255
          lightness_l: 40
          saturation_h: 255
          saturation_l: 90
