---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_h: 179
          hue_l: 0
          lightness_h: 255
          lightness_l: 200
          saturation_h: 60
          saturation_l: 0
        yellow:
          hue_h: 35
          hue_l: 15
          lightness_h: 255
          lightness_l: 80
          saturation_h: 255
          saturation_l: 80
